roswifibot_node:
  ros__parameters:
    port: "/dev/ttyUSB0"
    base_frame: "wifibot_base_frame"
    odom_frame: "wifibot_base_frame_odom"
    entrax: 0.39
    relay1: true
    relay2: true
    relay3: true
    battery_min_voltage: 10.5
    battery_max_voltage: 12.5
